sonar.projectKey=AddressBook
sonar.working.directory=D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook
sonar.pullrequest.cache.basepath=D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook

DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.projectKey=AddressBook:DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.projectName=AddressBook
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.projectBaseDir=D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.sourceEncoding=utf-8
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.tests=
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.sources=\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\AddressBookUtility.cs",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\AddressMenu.cs",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\Contact.cs",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\IAddressBook.cs",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\Program.cs",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\obj\\AddressBook.csproj.nuget.dgspec.json",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\obj\\project.assets.json",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\bin\\Debug\\net10.0\\AddressBook.deps.json",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\bin\\Debug\\net10.0\\AddressBook.runtimeconfig.json",\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\obj\\Debug\\net10.0\\AddressBook.sourcelink.json"

DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.cs.analyzer.projectOutPaths=\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\.sonarqube\\out\\0"
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.cs.roslyn.reportFilePaths=\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\.sonarqube\\out\\0\\Issues.json"
DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.cs.scanner.telemetry=\
"D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\.sonarqube\\out\\0\\Telemetry.json"

DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8.sonar.working.directory=D:\\BridgeLabz-Training\\oops-csharp-practice\\scenario-based\\AddressBook\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=DCD9DC47-5A4E-4BC4-B976-5FBA6649C5D8

